import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { LoaderCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageShell } from "@/components/site-shell";
import { lovable } from "@/integrations/lovable";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/auth")({
  validateSearch: (search: Record<string, unknown>) => ({ next: typeof search["next"] === "string" && search["next"].startsWith("/") ? search["next"] : "/portal" }),
  head: () => ({ meta: [{ title: "Customer Sign In | Mapleleaf Moving Co" }, { name: "description", content: "Sign in to manage your Mapleleaf Moving Co quotes and bookings." }, { property: "og:title", content: "Customer Sign In | Mapleleaf Moving Co" }, { property: "og:description", content: "Manage your move details, quote and booking online." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: AuthPage,
});
function AuthPage() {
  const { next } = Route.useSearch(); const navigate = useNavigate(); const [mode, setMode] = useState<"signin"|"signup">("signin"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { supabase.auth.getSession().then(({ data }) => { if (data.session) navigate({ to: next }); }); }, [navigate, next]);
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setMessage(""); const result = mode === "signup" ? await supabase.auth.signUp({ email, password, options: { data: { full_name: name } } }) : await supabase.auth.signInWithPassword({ email, password }); setBusy(false); if (result.error) setMessage(result.error.message); else if (mode === "signup" && !result.data.session) setMessage("Check your email to confirm your account, then sign in."); else navigate({ to: next }); }
  async function google() { sessionStorage.setItem("move_next", next); await lovable.auth.signInWithOAuth("google", { redirect_uri: `${window.location.origin}/auth` }); }
  return <PageShell><main className="mx-auto max-w-lg px-4 py-14"><section className="border border-border bg-card p-7 shadow-xl md:p-10"><p className="text-sm font-bold uppercase text-maple">Customer account</p><h1 className="mt-2 font-display text-4xl text-brand">{mode === "signin" ? "Welcome back." : "Manage your move online."}</h1><p className="mt-3 text-sm text-muted-foreground">See saved quotes, booking status, your inventory and deposit details.</p><Button type="button" variant="outline" className="mt-7 w-full" onClick={google}>Continue with Google</Button><div className="my-5 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border"/>OR<span className="h-px flex-1 bg-border"/></div><form onSubmit={submit} className="space-y-4">{mode === "signup" && <label className="block text-sm font-semibold">Full name<input value={name} onChange={(e) => setName(e.target.value)} required className="mt-2 w-full border border-input bg-background p-3 font-normal"/></label>}<label className="block text-sm font-semibold">Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required className="mt-2 w-full border border-input bg-background p-3 font-normal"/></label><label className="block text-sm font-semibold">Password<input type="password" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} required className="mt-2 w-full border border-input bg-background p-3 font-normal"/></label>{message && <p role="alert" className="bg-muted p-3 text-sm">{message}</p>}<Button className="w-full bg-maple hover:bg-maple-deep" disabled={busy}>{busy ? <LoaderCircle className="animate-spin"/> : mode === "signin" ? "Sign in" : "Create account"}</Button></form><button type="button" onClick={() => { setMode(mode === "signin" ? "signup" : "signin"); setMessage(""); }} className="mt-5 w-full text-sm font-semibold text-maple hover:underline">{mode === "signin" ? "New customer? Create an account" : "Already have an account? Sign in"}</button><p className="mt-6 text-center text-xs text-muted-foreground"><Link to="/quote" className="underline">Continue without an account</Link></p></section></main></PageShell>;
}
