import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, CheckCircle2, LoaderCircle, LogOut, MapPin, WalletCards } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { PageShell } from "@/components/site-shell";
import { useAuth } from "@/hooks/useAuth";
import { confirmBooking, getMyMoveData } from "@/lib/booking.functions";
import { money } from "@/lib/quote-engine";

export const Route = createFileRoute("/_authenticated/portal")({ head: () => ({ meta: [{ title: "My Move | Mapleleaf Moving Co" }, { name: "description", content: "Manage your Mapleleaf Moving Co quotes, bookings and move details." }, { property: "og:title", content: "My Move | Mapleleaf Moving Co" }, { property: "og:description", content: "Your private moving quote and booking dashboard." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Portal });
function Portal() {
  const load = useServerFn(getMyMoveData); const confirm = useServerFn(confirmBooking); const queryClient = useQueryClient(); const { user, signOut } = useAuth(); const navigate = useNavigate(); const [selected, setSelected] = useState<string | null>(null); const [agreement, setAgreement] = useState(""); const [accept, setAccept] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const query = useQuery({ queryKey: ["my-move-data"], queryFn: () => load() });
  async function book() { if (!selected || !agreement.trim() || !accept) { setError("Enter your name and accept the agreement to continue."); return; } setBusy(true); setError(""); try { await confirm({ data: { quoteId: selected, agreementName: agreement } }); setSelected(null); await queryClient.invalidateQueries({ queryKey: ["my-move-data"] }); } catch (caught) { setError(caught instanceof Error ? caught.message : "Booking failed."); } finally { setBusy(false); } }
  return <PageShell><main className="mx-auto max-w-7xl px-4 py-10 md:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase text-maple">Customer dashboard</p><h1 className="mt-1 font-display text-4xl text-brand">My move</h1><p className="mt-2 text-sm text-muted-foreground">{user?.email}</p></div><div className="flex gap-2"><Button asChild><Link to="/quote">New quote</Link></Button><Button variant="outline" onClick={async () => { await signOut(); navigate({ to: "/" }); }}><LogOut/>Sign out</Button></div></div>
  {query.isLoading && <div className="flex justify-center py-24"><LoaderCircle className="size-8 animate-spin text-maple"/></div>}{query.error && <p className="mt-8 bg-card p-5">Your move details could not be loaded.</p>}
  {query.data && <div className="mt-8 grid gap-7 lg:grid-cols-2"><section><h2 className="mb-3 font-display text-2xl text-brand">Bookings</h2>{query.data.bookings.length === 0 ? <div className="border border-border bg-card p-6 text-sm text-muted-foreground">No confirmed bookings yet.</div> : <div className="space-y-3">{query.data.bookings.map((booking) => <article key={booking.id} className="border border-border bg-card p-5 shadow"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase text-maple">{booking.reference}</p><h3 className="mt-1 font-display text-xl text-brand">{new Date(`${booking.move_date}T12:00:00`).toLocaleDateString("en-CA", { month: "long", day: "numeric", year: "numeric" })}</h3></div><span className="bg-amber/15 px-2 py-1 text-xs font-bold text-maple-deep">Awaiting deposit</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><p><CalendarDays className="mr-1 inline size-4 text-maple"/>{booking.arrival_window}</p><p><WalletCards className="mr-1 inline size-4 text-maple"/>{money(booking.deposit_cents)} pending</p></div><div className="mt-5 border-l-4 border-amber bg-muted p-3 text-sm">We’ll contact you to arrange the deposit while online payments are being activated.</div></article>)}</div>}</section>
  <section><h2 className="mb-3 font-display text-2xl text-brand">Saved quotes</h2>{query.data.quotes.length === 0 ? <div className="border border-border bg-card p-6 text-sm"><p className="text-muted-foreground">No saved quotes in this account.</p><Button asChild className="mt-4"><Link to="/quote">Build a quote</Link></Button></div> : <div className="space-y-3">{query.data.quotes.map((quote) => <article key={quote.id} className="border border-border bg-card p-5 shadow"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-maple">{quote.reference}</p><p className="mt-1 font-display text-2xl text-brand">{money(quote.price_low_cents)}–{money(quote.price_high_cents)}</p></div><span className="text-xs font-semibold uppercase text-muted-foreground">{quote.status}</span></div><p className="mt-4 flex gap-2 text-sm"><MapPin className="mt-0.5 size-4 shrink-0 text-maple"/><span>{quote.from_address}<br/>to {quote.to_address}</span></p><div className="mt-3 flex flex-wrap gap-4 text-xs text-muted-foreground"><span>{quote.move_date || "Date flexible"}</span><span>Crew of {quote.crew_size}</span><span>{quote.estimated_hours} hours</span></div>{quote.status !== "booked" && <Button className="mt-5 w-full bg-maple hover:bg-maple-deep" onClick={() => { setSelected(quote.id); setAgreement(quote.contact_name ?? ""); }}>Request this booking</Button>}</article>)}</div>}</section></div>}
  {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-brand/80 p-4"><section role="dialog" aria-modal="true" className="w-full max-w-lg bg-card p-6 shadow-2xl md:p-8"><CheckCircle2 className="size-8 text-maple"/><h2 className="mt-3 font-display text-3xl text-brand">Confirm your move request</h2><p className="mt-3 text-sm text-muted-foreground">By entering your name, you confirm the quote details are accurate and authorize Mapleleaf Moving Co to contact you to finalize scheduling. Your date is not secured until the deposit is arranged.</p><label className="mt-5 block text-sm font-semibold">Full legal name<input value={agreement} onChange={(e) => setAgreement(e.target.value)} className="mt-2 w-full border border-input bg-background p-3 font-normal"/></label><label className="mt-4 flex items-start gap-3 text-sm"><input type="checkbox" checked={accept} onChange={(e) => setAccept(e.target.checked)} className="mt-1 size-4 accent-maple"/><span>I accept the booking agreement and understand the deposit remains pending.</span></label>{error && <p className="mt-4 bg-maple/10 p-3 text-sm text-maple-deep">{error}</p>}<div className="mt-6 flex justify-end gap-2"><Button variant="outline" onClick={() => setSelected(null)}>Cancel</Button><Button onClick={book} disabled={busy} className="bg-maple hover:bg-maple-deep">{busy ? <LoaderCircle className="animate-spin"/> : "Accept & request booking"}</Button></div></section></div>}
  </main></PageShell>;
}
